[package]
name = "simple-commits"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
inquire = "0.7.1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt", "macros", "sync", "rt-multi-thread"] }
toml = "0.8.8"
