name: Check Format and Code Quality
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "src/**/**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"

jobs:
  check-fmt:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: check format
        run: |
          cargo fmt --all --check

  check-clippy:
    needs: [check-fmt]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: cargo clippy
        run: |
          cargo clippy -- -D warnings
